<?php
return [
    'openai_api_key' => 'PASTE_YOUR_OPENAI_API_KEY_HERE',
    'default_model' => 'gpt-5-mini',
    'cors_allow_origins' => [
        'http://localhost:5173',
        'http://127.0.0.1:5173',
    ],
    'db_servername' => 'localhost',
    'db_username' => 'your_db_username',
    'db_password' => 'your_db_password',
    'db_name' => 'your_db_name',
    'db_port' => 3306,
    'app_base_url' => 'https://yourdomain.com/dd',
    'app_host' => 'enddne.com',
    'app_origin' => 'https://enddne.com',
    'smtp_enabled' => false,
    'phpmailer_src_path' => __DIR__ . '/third_party/PHPMailer/src',
    'smtp_host' => 'smtp.example.com',
    'smtp_port' => 587,
    'smtp_username' => 'smtp_user',
    'smtp_password' => 'smtp_password',
    'smtp_secure' => 'tls',
    'smtp_timeout_seconds' => 15,
    'smtp_from_email' => 'no-reply@yourdomain.com',
    'smtp_from_name' => 'A-Ideation',
    'auth_return_tokens_in_response' => false,
    'auth_session_timeout_seconds' => 43200,
];
